language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env:
  secure: "QSumTvMGgT7gm/ydWBbB4kkivLWTPyWZzsPxfF1fx2Ekn+I9836s4L8sp4lKLVMlCWMTP1BTIYMB8gIY7lkdWusYz8GnHuLwVgwo0MtiKsM4dx/INBYz3X7jFlQ5zzHzYdjsZGhw0J9Ez4ef7K60+ssUUxOZIA+nZM2d+vgSrMvhVLOUmGZ+UOlv1yr9ed6hvbdNT6Nk98zqBiiEb5oly+bt6RqWeYYf7lsFAnQX7haCBZWs+Hts4ewRZziUzP1zUMB2qMNNkpZPOYXwXBfd00vCBMGk3YEaqBD7YXH8gMmgPLxCoeoriQsXx53X6IG/gAZ5ZpFW6A+TpFiYFlQB8A0pf4EWeTgR4IJ+OpWT9GLM0Z4ObYKFGe2/ZJjWH/zknB2NAjuVNmtbRgwQFaTP9JXBIFiK9VF7gW7jehXrVSGvkeVJIuOpyB+Z6y8qmKiDPWBMmBCESNhIp5DuvSmS2etGaf+/Ptb07dxoawb/YoSmOie4wGW0+1czDI5iMQFmy+pAvmcNiCNLRnK5UdwUfqv5aB2DQnEIeAe4EE1Dt1eHs+fSROuiSfQ11CekmMRMMWTO9dZF5lSmFp57HzESDddg67Pj5hKAWHre7MoZGrH+Yo3cQUm/CB+Qjxm4wP4UVUiB8n+APw2vGf9jdob+nJVANPSjI7qINOFkTb2MmdY="

  
  
addons:
  sonarcloud:
    organization: "vsrs-laurentius"
    token:   
      secure: "Dh5CtlEAJzl4xZB3nHRNSDOdOxB8Vvfj0t113mDRyH97CpGwUXNo5mht2/u0JyartFsl8Hrzn0GNWbRXnTQ+zlPnTfSWSuBwPzLTm1A2NlOswNwuI+3x4+ES2ebIAnpM4u/ZTDUpuwRTW9c3VAhyoqkkTZQyaH9Qvwj8djHRjCGyJh5rmqu/Aw0F5f2IyXZ00qm4Vfj/sSCqXVaAdTaRZOSfUnE+OS3QRMilhHu2J0Cl70jNYg2ka4X2093WnXsoORsiuexUH7KHkqW+UDGGjQLUOlYBuzdISVvCpjvFZTS9p9/jjK5YuUAp90x0KFeLEBO+IIAhF31BmDa5KsgYGHvDrqFufEjoH023S9jQ/azM5HDf4PBBIU+pZLr+87GIMvavMyBvd/E3qHae1Gf5oP60umhSVzagU9uJGbTYQM2SqMtMZcXyHnsHTUA7UuLWPXOW63BrHZ5L5qX8jY9+M8S9LBsDoLDRRd/87SIZbTwcE48NcYpnpuBgJiIr2gGQEFTskAV4AsXb4ASyINoVkc2KWFhX/lQduJCLV8JX8CQtu/GodlM0o6WXUxyY93e5zOtjNLoJRrOXDVz0Ah+CZ+j+AMx4k/86CIivB9rntl5vyNJthQa+oVmaRM3wnarJ8oIKs5WYlNIt1fEaLn7nTwNaC2OjmB6hHYWCiyF/A0c="



#
jobs:
  include:
    - stage: build_and_analyse
      script: 
         - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar           
    - stage: build_docker_image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t laurentius-cef-plugin .
      - docker tag laurentius-cef-plugin $DOCKER_USERNAME/laurentius-cef-plugin
      - docker push $DOCKER_USERNAME/laurentius-cef-plugin
